spring:
  datasource:
    dynamic: true
    hikari:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@9.7.22.1:1521/bsdev
#      jdbc-url: jdbc:oracle:thin:@192.168.20.205:1521/bsdev
      username: risksurvey_d01
      password: risksurvey_d01
      read-only: false
      connection-timeout: 300000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 5